# Define simulation version (change manually for each iteration)
version: "v0.1"

# IOb-cache source locations
cache_location: "../iob_cache_V0.7/"
sum_location: "../8int-sum/"
sim_location: "../iob_cache_V0.7/hardware/simulation/src/"
src_location: "../iob_cache_V0.7/hardware/src/"


# Testbench top module
wave_out_top_module: "wave_top"
sim_out_top_module: "tb_top_wrapper"
log_out_top_module: "log_top.txt"

tb_files_top_module:
  - "full_system_wrapper.v"
  - "full_system_wrapper_tb.v"
  - "memory_wrapper.v"

# Testbench memory module loaded
wave_out_mem_loaded_module: "wave_loaded_mem"
sim_out_mem_loaded_module: "tb_loaded_mem_wrapper"
log_out_mem_loaded_module: "log_loaded_mem.txt"

tb_files_mem_loaded_module:
  - "memory_wrapper_loaded_tb.v"
  - "memory_wrapper.v"

# Testbench memory module
wave_out_mem_module: "wave_mem"
sim_out_mem_module: "tb_mem_wrapper"
log_out_mem_module: "log_mem.txt"

tb_files_mem_module:
  - "memory_wrapper_tb.v"
  - "memory_wrapper.v"

# Testbench accelerator module
wave_out_acc_module: "wave_acc"
sim_out_acc_module: "tb_acc_wrapper"
log_out_acc_module: "log_acc.txt"

tb_files_acc_module:
  - "../8int-sum/4num-sum_tb.v"

# Testbench ram module
wave_out_ram_module: "wave_ram"
sim_out_ram_module: "tb_ram_wrapper"
log_out_ram_module: "log_ram.txt"

tb_files_ram_module:
  - "../vector_ram/vec_ram_tb.v"

# Testbench fifo module
wave_out_fifo_module: "wave_fifo"
sim_out_fifo_module: "tb_fifo_wrapper"
log_out_fifo_module: "log_fifo.txt"

tb_files_fifo_module:
  - "fifo_tb.v"

#Testbench lsu module
wave_out_lsu_module: "wave_lsu"
sim_out_lsu_module: "tb_lsu_wrapper"
log_out_lsu_module: "log_lsu.txt"

tb_files_lsu_module:
  - "load_store_unit_tb.v"

# Testbench lsu wrapper module
wave_out_lsu_wrapper_module: "wave_lsu_wrapper"
sim_out_lsu_wrapper_module: "tb_lsu_wrapper_wrapper"
log_out_lsu_wrapper_module: "log_lsu_wrapper.txt" 

wave_out_acc_max_min_module: "wave_acc_max_min"
sim_out_acc_max_min_module: "tb_acc_max_min_wrapper"
log_out_acc_max_min_module: "log_acc_max_min.txt"

tb_files_acc_max_min_module:
  - "../verilog/accelerator_max_min_tb.v"

wave_out_acc_property_module: "wave_acc_property"
sim_out_acc_property_module: "tb_acc_property_wrapper"
log_out_acc_property_module: "log_acc_property.txt"

tb_files_acc_property_module:
  - "../verilog/accelerator_count_tb.v"

tb_files_lsu_wrapper_module:
  - "lsu_wrapper_tb.v"

# Accelerator files list
acc_files:
  - "../8int-sum/4num-sum.v"

sdf_file_acc_module:
  - "../../my_designs/acc/runs/RUN_2025-05-20_12-50-28/final/sdf/nom_tt_025C_1v80/nom_tt_025C_1v80.sdf"

# Ram files list
ram_files:
  - "../vector_ram/vec_ram.v"

# Controller files list
ctrl_files:
  - "memory_controller.v"

# FIFO files list
fifo_files:
  - "fifo.v"

# LSU files list
lsu_files:
  - "load_store_unit.v"

# LSU wrapper files list
lsu_wrapper_files:
  - "lsu_wrapper.v"

acc_max_min_files:
  - "../verilog/accelerator_max_min.v"

# Property files list
acc_property_files:
  - "../verilog/accelerator_property.v"

# IOb-cache files list
IoB_files:
  - "../iob_cache_V0.7/hardware/src/iob_cache_iob.v"
  - "../iob_cache_V0.7/hardware/src/iob_ram_sp_be.v"
  - "../iob_cache_V0.7/hardware/src/iob_reg_re.v"
  - "../iob_cache_V0.7/hardware/src/iob_cache_back_end.v"
  - "../iob_cache_V0.7/hardware/src/iob_cache_front_end.v"
  - "../iob_cache_V0.7/hardware/src/iob_cache_memory.v"
  - "../iob_cache_V0.7/hardware/src/iob_reg_r.v"
  - "../iob_cache_V0.7/hardware/src/iob_cache_onehot_to_bin.v"
  - "../iob_cache_V0.7/hardware/src/iob_cache_read_channel.v"
  - "../iob_cache_V0.7/hardware/src/iob_cache_replacement_policy.v"
  - "../iob_cache_V0.7/hardware/src/iob_cache_write_channel.v"
  - "../iob_cache_V0.7/hardware/src/iob_fifo_sync.v"
  - "../iob_cache_V0.7/hardware/src/iob_ram_sp.v"
  - "../iob_cache_V0.7/hardware/src/iob_ram_t2p.v"
  - "../iob_cache_V0.7/hardware/src/iob_reg.v"
  - "../iob_cache_V0.7/hardware/src/iob_asym_converter.v"
  - "../iob_cache_V0.7/hardware/src/iob_counter.v"
  - "../iob_cache_V0.7/hardware/src/iob_regfile_sp.v"

pdk_files: 
  - "/home/rodrialves/.volare/sky130B/libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v"
  - "/home/rodrialves/.volare/sky130B/libs.ref/sky130_fd_sc_hd/verilog/primitives.v"