// Auto-generated by OpenLane
module lsu_wrapper(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input arst_i,
  input start,
  output done,
  input[21:0] load_base_addr,
  input[21:0] store_base_addr,
  input[21:0] count,
  output load_req,
  output[21:0] load_addr,
  input[31:0] load_data,
  input load_complete,
  output store_req,
  output[21:0] store_addr,
  output[31:0] store_data,
  input store_complete
);
endmodule
